apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: devops-lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        # Check this section carefully:
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html # Must be 'mountPath' (case sensitive)
          subPath: WELCOME_MSG
      volumes:
      - name: config-volume
        configMap:
          name: app-settings
