# 1. THE DEPLOYMENT: Defines how many pods to run and their config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: devops-lab # Must match Ansible and Terraform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        # Check this section carefully:
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html # Must be 'mountPath' (case sensitive)
          subPath: WELCOME_MSG
      volumes:
      - name: config-volume
        configMap:
          name: app-settings
---
# 2. THE SERVICE: The internal "stable" IP for your pods
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devops-lab
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      target_port: 80
  type: ClusterIP # Changed from NodePort because Ingress handles external access now
---
# 3. THE INGRESS: The "Front Door" for http://devops.lab
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  namespace: devops-lab
  annotations:
    # This tells the Nginx controller how to handle traffic
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    # --- STICKY SESSION CONFIGURATION ---
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: devops.lab  # This is your "local" domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
