apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: devops-lab # Must match Ansible and Terraform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mount_path: /usr/share/nginx/html/index.html
          sub_path: WELCOME_MSG
      volumes:
      - name: config-volume
        config_map:
          name: app-settings # ArgoCD finds this in the same namespace
